# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e34d3ca96b32fa03e48a9476c390a396b134f555ca31ca983c62e8975a920b0ce826dab648db9d976cbe5a77f5755c8e22b0f13989f51508d679f57bb22be7b5

test:
  secret_key_base: 50a33e3282994ae0716805173e034193cc235cc22e667ef3030b08e853cb96a650b2ab5f5af72363f5d57c5e95642768d3e712ad544350d9a5c2bcb6c01d449e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
